language: java
jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2

notifications:
  email: true

before_install:
  - ulimit -u 65535
  - mvn -f dev-tools/pom.xml install 
  - mvn -f rest-api-spec/pom.xml install 
  - mvn -f javassist-maven/pom.xml install 

install: 
  -mvn -f core/pom.xml install -DskipTests
  -mvn package 
