language: java
jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2

notifications:
  email: true

before_install:
  - ulimit -u 65535
  - mvn -f javassist-maven/pom.xml install 

install: mvn -DskipTests package 
